/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : string,
  'afterBreak' : [] | [string],
  'breakTime' : [] | [string],
  'date' : string,
  'exit' : [] | [string],
  'entry' : [] | [string],
  'personId' : string,
}
export interface AttendanceUpdateInput {
  'afterBreak' : [] | [string],
  'breakTime' : [] | [string],
  'exit' : [] | [string],
  'entry' : [] | [string],
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponsePayload {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface Person {
  'id' : string,
  'semester' : [] | [string],
  'name' : string,
  'personType' : PersonType,
  'nsqfLevel' : [] | [string],
  'faceDescriptor' : Array<number>,
  'rollNo' : [] | [string],
  'course' : [] | [string],
}
export interface PersonInput {
  'semester' : [] | [string],
  'name' : string,
  'personType' : PersonType,
  'nsqfLevel' : [] | [string],
  'faceDescriptor' : Array<number>,
  'rollNo' : [] | [string],
  'course' : [] | [string],
}
export type PersonType = { 'JIG' : null } |
  { 'NSQF' : null };
export interface TransformArgs {
  'context' : Uint8Array,
  'response' : HttpResponsePayload,
}
export interface _SERVICE {
  'addPerson' : ActorMethod<
    [PersonInput],
    { 'ok' : Person } |
      { 'err' : string }
  >,
  'clearAllData' : ActorMethod<[], undefined>,
  'deleteAttendance' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deletePerson' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'getActiveMonths' : ActorMethod<[], bigint>,
  'getAllFaceDescriptors' : ActorMethod<[], Array<[string, Array<number>]>>,
  'getAttendance' : ActorMethod<[string, string], [] | [AttendanceRecord]>,
  'getPerson' : ActorMethod<[string], [] | [Person]>,
  'getTodayCheckIns' : ActorMethod<[], bigint>,
  'getTotalCheckIns' : ActorMethod<[], bigint>,
  'getTotalStudents' : ActorMethod<[], bigint>,
  'listAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'listAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'listPersons' : ActorMethod<[], Array<Person>>,
  'recordAttendance' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'syncAttendanceWithJwt' : ActorMethod<[string, string, string], string>,
  'testGoogleSheetsSync' : ActorMethod<[string], string>,
  'transformBatchUpdateResponse' : ActorMethod<
    [TransformArgs],
    HttpResponsePayload
  >,
  'transformSheetsResponse' : ActorMethod<[TransformArgs], HttpResponsePayload>,
  'transformTokenResponse' : ActorMethod<[TransformArgs], HttpResponsePayload>,
  'updateAttendance' : ActorMethod<
    [string, AttendanceUpdateInput],
    { 'ok' : AttendanceRecord } |
      { 'err' : string }
  >,
  'updatePerson' : ActorMethod<
    [string, PersonInput],
    { 'ok' : Person } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];