/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : bigint,
  'day' : bigint,
  'month' : bigint,
  'dateStr' : string,
  'name' : string,
  'slot' : string,
  'year' : bigint,
  'monthStr' : string,
  'personType' : { 'employee' : null } |
    { 'student' : null },
  'personId' : bigint,
  'timestamp' : bigint,
  'editedAt' : [] | [Time],
  'timeStr' : string,
}
export interface DescriptorEntry {
  'id' : bigint,
  'name' : string,
  'personType' : { 'employee' : null } |
    { 'student' : null },
  'faceDescriptor' : Array<number>,
}
export interface Person {
  'id' : bigint,
  'studentId' : string,
  'name' : string,
  'createdAt' : Time,
  'personType' : { 'employee' : null } |
    { 'student' : null },
  'employeeId' : string,
  'faceDescriptor' : Array<number>,
  'batch' : string,
  'rollNo' : string,
}
export interface PersonSummary {
  'id' : bigint,
  'studentId' : string,
  'name' : string,
  'createdAt' : Time,
  'personType' : { 'employee' : null } |
    { 'student' : null },
  'employeeId' : string,
  'batch' : string,
  'rollNo' : string,
}
export interface Stats {
  'activeMonths' : Array<string>,
  'totalPersons' : bigint,
  'totalAttendance' : bigint,
  'todayCheckins' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'deleteAttendanceRecord' : ActorMethod<[bigint], undefined>,
  'deletePerson' : ActorMethod<[bigint], undefined>,
  'getAllFaceDescriptors' : ActorMethod<[], Array<DescriptorEntry>>,
  'getAllPersons' : ActorMethod<[], Array<PersonSummary>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByMonth' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getPerson' : ActorMethod<[bigint], Person>,
  'getPersonSummary' : ActorMethod<[bigint], PersonSummary>,
  'getStats' : ActorMethod<[], Stats>,
  'getTodayCheckins' : ActorMethod<[string], bigint>,
  'hasAttendedSlot' : ActorMethod<[bigint, string, string], boolean>,
  'recordAttendance' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
    ],
    bigint
  >,
  'registerPerson' : ActorMethod<
    [string, string, string, string, string, string, Array<number>],
    bigint
  >,
  'updateAttendanceRecord' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updatePerson' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updatePersonDescriptor' : ActorMethod<[bigint, Array<number>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];