/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PersonType = IDL.Variant({ 'JIG' : IDL.Null, 'NSQF' : IDL.Null });
export const PersonInput = IDL.Record({
  'semester' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'personType' : PersonType,
  'nsqfLevel' : IDL.Opt(IDL.Text),
  'faceDescriptor' : IDL.Vec(IDL.Float64),
  'rollNo' : IDL.Opt(IDL.Text),
  'course' : IDL.Opt(IDL.Text),
});
export const Person = IDL.Record({
  'id' : IDL.Text,
  'semester' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'personType' : PersonType,
  'nsqfLevel' : IDL.Opt(IDL.Text),
  'faceDescriptor' : IDL.Vec(IDL.Float64),
  'rollNo' : IDL.Opt(IDL.Text),
  'course' : IDL.Opt(IDL.Text),
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'afterBreak' : IDL.Opt(IDL.Text),
  'breakTime' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'exit' : IDL.Opt(IDL.Text),
  'entry' : IDL.Opt(IDL.Text),
  'personId' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponsePayload = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformArgs = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpResponsePayload,
});
export const AttendanceUpdateInput = IDL.Record({
  'afterBreak' : IDL.Opt(IDL.Text),
  'breakTime' : IDL.Opt(IDL.Text),
  'exit' : IDL.Opt(IDL.Text),
  'entry' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addPerson' : IDL.Func(
      [PersonInput],
      [IDL.Variant({ 'ok' : Person, 'err' : IDL.Text })],
      [],
    ),
  'clearAllData' : IDL.Func([], [], []),
  'deleteAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deletePerson' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActiveMonths' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllFaceDescriptors' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Float64)))],
      ['query'],
    ),
  'getAttendance' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(AttendanceRecord)],
      ['query'],
    ),
  'getPerson' : IDL.Func([IDL.Text], [IDL.Opt(Person)], ['query']),
  'getTodayCheckIns' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalCheckIns' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalStudents' : IDL.Func([], [IDL.Nat], ['query']),
  'listAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'listAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'listPersons' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'recordAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'syncAttendanceWithJwt' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'testGoogleSheetsSync' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transformBatchUpdateResponse' : IDL.Func(
      [TransformArgs],
      [HttpResponsePayload],
      ['query'],
    ),
  'transformSheetsResponse' : IDL.Func(
      [TransformArgs],
      [HttpResponsePayload],
      ['query'],
    ),
  'transformTokenResponse' : IDL.Func(
      [TransformArgs],
      [HttpResponsePayload],
      ['query'],
    ),
  'updateAttendance' : IDL.Func(
      [IDL.Text, AttendanceUpdateInput],
      [IDL.Variant({ 'ok' : AttendanceRecord, 'err' : IDL.Text })],
      [],
    ),
  'updatePerson' : IDL.Func(
      [IDL.Text, PersonInput],
      [IDL.Variant({ 'ok' : Person, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PersonType = IDL.Variant({ 'JIG' : IDL.Null, 'NSQF' : IDL.Null });
  const PersonInput = IDL.Record({
    'semester' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'personType' : PersonType,
    'nsqfLevel' : IDL.Opt(IDL.Text),
    'faceDescriptor' : IDL.Vec(IDL.Float64),
    'rollNo' : IDL.Opt(IDL.Text),
    'course' : IDL.Opt(IDL.Text),
  });
  const Person = IDL.Record({
    'id' : IDL.Text,
    'semester' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'personType' : PersonType,
    'nsqfLevel' : IDL.Opt(IDL.Text),
    'faceDescriptor' : IDL.Vec(IDL.Float64),
    'rollNo' : IDL.Opt(IDL.Text),
    'course' : IDL.Opt(IDL.Text),
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'afterBreak' : IDL.Opt(IDL.Text),
    'breakTime' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'exit' : IDL.Opt(IDL.Text),
    'entry' : IDL.Opt(IDL.Text),
    'personId' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponsePayload = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpResponsePayload,
  });
  const AttendanceUpdateInput = IDL.Record({
    'afterBreak' : IDL.Opt(IDL.Text),
    'breakTime' : IDL.Opt(IDL.Text),
    'exit' : IDL.Opt(IDL.Text),
    'entry' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addPerson' : IDL.Func(
        [PersonInput],
        [IDL.Variant({ 'ok' : Person, 'err' : IDL.Text })],
        [],
      ),
    'clearAllData' : IDL.Func([], [], []),
    'deleteAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deletePerson' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActiveMonths' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllFaceDescriptors' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Float64)))],
        ['query'],
      ),
    'getAttendance' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(AttendanceRecord)],
        ['query'],
      ),
    'getPerson' : IDL.Func([IDL.Text], [IDL.Opt(Person)], ['query']),
    'getTodayCheckIns' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalCheckIns' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalStudents' : IDL.Func([], [IDL.Nat], ['query']),
    'listAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'listAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'listPersons' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'recordAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'syncAttendanceWithJwt' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'testGoogleSheetsSync' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transformBatchUpdateResponse' : IDL.Func(
        [TransformArgs],
        [HttpResponsePayload],
        ['query'],
      ),
    'transformSheetsResponse' : IDL.Func(
        [TransformArgs],
        [HttpResponsePayload],
        ['query'],
      ),
    'transformTokenResponse' : IDL.Func(
        [TransformArgs],
        [HttpResponsePayload],
        ['query'],
      ),
    'updateAttendance' : IDL.Func(
        [IDL.Text, AttendanceUpdateInput],
        [IDL.Variant({ 'ok' : AttendanceRecord, 'err' : IDL.Text })],
        [],
      ),
    'updatePerson' : IDL.Func(
        [IDL.Text, PersonInput],
        [IDL.Variant({ 'ok' : Person, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };