/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DescriptorEntry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'personType' : IDL.Variant({ 'employee' : IDL.Null, 'student' : IDL.Null }),
  'faceDescriptor' : IDL.Vec(IDL.Float64),
});
export const Time = IDL.Int;
export const PersonSummary = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'personType' : IDL.Variant({ 'employee' : IDL.Null, 'student' : IDL.Null }),
  'employeeId' : IDL.Text,
  'batch' : IDL.Text,
  'rollNo' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'day' : IDL.Int,
  'month' : IDL.Int,
  'dateStr' : IDL.Text,
  'name' : IDL.Text,
  'slot' : IDL.Text,
  'year' : IDL.Int,
  'monthStr' : IDL.Text,
  'personType' : IDL.Variant({ 'employee' : IDL.Null, 'student' : IDL.Null }),
  'personId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'editedAt' : IDL.Opt(Time),
  'timeStr' : IDL.Text,
});
export const Person = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'personType' : IDL.Variant({ 'employee' : IDL.Null, 'student' : IDL.Null }),
  'employeeId' : IDL.Text,
  'faceDescriptor' : IDL.Vec(IDL.Float64),
  'batch' : IDL.Text,
  'rollNo' : IDL.Text,
});
export const Stats = IDL.Record({
  'activeMonths' : IDL.Vec(IDL.Text),
  'totalPersons' : IDL.Nat,
  'totalAttendance' : IDL.Nat,
  'todayCheckins' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deleteAttendanceRecord' : IDL.Func([IDL.Nat], [], []),
  'deletePerson' : IDL.Func([IDL.Nat], [], []),
  'getAllFaceDescriptors' : IDL.Func([], [IDL.Vec(DescriptorEntry)], ['query']),
  'getAllPersons' : IDL.Func([], [IDL.Vec(PersonSummary)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceRecords' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getPerson' : IDL.Func([IDL.Nat], [Person], ['query']),
  'getPersonSummary' : IDL.Func([IDL.Nat], [PersonSummary], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTodayCheckins' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'hasAttendedSlot' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'recordAttendance' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'registerPerson' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Float64),
      ],
      [IDL.Nat],
      [],
    ),
  'updateAttendanceRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePerson' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePersonDescriptor' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Float64)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DescriptorEntry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'personType' : IDL.Variant({ 'employee' : IDL.Null, 'student' : IDL.Null }),
    'faceDescriptor' : IDL.Vec(IDL.Float64),
  });
  const Time = IDL.Int;
  const PersonSummary = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'personType' : IDL.Variant({ 'employee' : IDL.Null, 'student' : IDL.Null }),
    'employeeId' : IDL.Text,
    'batch' : IDL.Text,
    'rollNo' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'day' : IDL.Int,
    'month' : IDL.Int,
    'dateStr' : IDL.Text,
    'name' : IDL.Text,
    'slot' : IDL.Text,
    'year' : IDL.Int,
    'monthStr' : IDL.Text,
    'personType' : IDL.Variant({ 'employee' : IDL.Null, 'student' : IDL.Null }),
    'personId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'editedAt' : IDL.Opt(Time),
    'timeStr' : IDL.Text,
  });
  const Person = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'personType' : IDL.Variant({ 'employee' : IDL.Null, 'student' : IDL.Null }),
    'employeeId' : IDL.Text,
    'faceDescriptor' : IDL.Vec(IDL.Float64),
    'batch' : IDL.Text,
    'rollNo' : IDL.Text,
  });
  const Stats = IDL.Record({
    'activeMonths' : IDL.Vec(IDL.Text),
    'totalPersons' : IDL.Nat,
    'totalAttendance' : IDL.Nat,
    'todayCheckins' : IDL.Nat,
  });
  
  return IDL.Service({
    'deleteAttendanceRecord' : IDL.Func([IDL.Nat], [], []),
    'deletePerson' : IDL.Func([IDL.Nat], [], []),
    'getAllFaceDescriptors' : IDL.Func(
        [],
        [IDL.Vec(DescriptorEntry)],
        ['query'],
      ),
    'getAllPersons' : IDL.Func([], [IDL.Vec(PersonSummary)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getPerson' : IDL.Func([IDL.Nat], [Person], ['query']),
    'getPersonSummary' : IDL.Func([IDL.Nat], [PersonSummary], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTodayCheckins' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'hasAttendedSlot' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'recordAttendance' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'registerPerson' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Float64),
        ],
        [IDL.Nat],
        [],
      ),
    'updateAttendanceRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePerson' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePersonDescriptor' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Float64)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };