/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HttpResponsePayload {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface PersonInput {
    semester?: string;
    name: string;
    personType: PersonType;
    nsqfLevel?: string;
    faceDescriptor: Array<number>;
    rollNo?: string;
    course?: string;
}
export interface AttendanceUpdateInput {
    afterBreak?: string;
    breakTime?: string;
    exit?: string;
    entry?: string;
}
export interface AttendanceRecord {
    id: string;
    afterBreak?: string;
    breakTime?: string;
    date: string;
    exit?: string;
    entry?: string;
    personId: string;
}
export interface Person {
    id: string;
    semester?: string;
    name: string;
    personType: PersonType;
    nsqfLevel?: string;
    faceDescriptor: Array<number>;
    rollNo?: string;
    course?: string;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface TransformArgs {
    context: Uint8Array;
    response: HttpResponsePayload;
}
export enum PersonType {
    JIG = "JIG",
    NSQF = "NSQF"
}
export interface backendInterface {
    addPerson(input: PersonInput): Promise<{
        __kind__: "ok";
        ok: Person;
    } | {
        __kind__: "err";
        err: string;
    }>;
    clearAllData(): Promise<void>;
    deleteAttendance(id: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deletePerson(id: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActiveMonths(): Promise<bigint>;
    getAllFaceDescriptors(): Promise<Array<[string, Array<number>]>>;
    getAttendance(personId: string, date: string): Promise<AttendanceRecord | null>;
    getPerson(id: string): Promise<Person | null>;
    getTodayCheckIns(): Promise<bigint>;
    getTotalCheckIns(): Promise<bigint>;
    getTotalStudents(): Promise<bigint>;
    listAttendance(): Promise<Array<AttendanceRecord>>;
    listAttendanceByDate(date: string): Promise<Array<AttendanceRecord>>;
    listPersons(): Promise<Array<Person>>;
    recordAttendance(personId: string, date: string, slot: string, time: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    syncAttendanceWithJwt(jwt: string, rowDataJson: string, sheetTabName: string): Promise<string>;
    testGoogleSheetsSync(jwt: string): Promise<string>;
    transformBatchUpdateResponse(raw: TransformArgs): Promise<HttpResponsePayload>;
    transformSheetsResponse(raw: TransformArgs): Promise<HttpResponsePayload>;
    transformTokenResponse(raw: TransformArgs): Promise<HttpResponsePayload>;
    updateAttendance(id: string, updates: AttendanceUpdateInput): Promise<{
        __kind__: "ok";
        ok: AttendanceRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updatePerson(id: string, input: PersonInput): Promise<{
        __kind__: "ok";
        ok: Person;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AttendanceRecord as _AttendanceRecord, AttendanceUpdateInput as _AttendanceUpdateInput, Person as _Person, PersonInput as _PersonInput, PersonType as _PersonType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPerson(arg0: PersonInput): Promise<{
        __kind__: "ok";
        ok: Person;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addPerson(to_candid_PersonInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPerson(to_candid_PersonInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return result;
        }
    }
    async deleteAttendance(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAttendance(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAttendance(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePerson(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePerson(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePerson(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveMonths(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveMonths();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveMonths();
            return result;
        }
    }
    async getAllFaceDescriptors(): Promise<Array<[string, Array<number>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFaceDescriptors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFaceDescriptors();
            return result;
        }
    }
    async getAttendance(arg0: string, arg1: string): Promise<AttendanceRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerson(arg0: string): Promise<Person | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerson(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerson(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayCheckIns(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayCheckIns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayCheckIns();
            return result;
        }
    }
    async getTotalCheckIns(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalCheckIns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalCheckIns();
            return result;
        }
    }
    async getTotalStudents(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalStudents();
            return result;
        }
    }
    async listAttendance(): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAttendance();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAttendance();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAttendanceByDate(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAttendanceByDate(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAttendanceByDate(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPersons(): Promise<Array<Person>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPersons();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPersons();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordAttendance(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttendance(arg0, arg1, arg2, arg3);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttendance(arg0, arg1, arg2, arg3);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async syncAttendanceWithJwt(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.syncAttendanceWithJwt(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncAttendanceWithJwt(arg0, arg1, arg2);
            return result;
        }
    }
    async testGoogleSheetsSync(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.testGoogleSheetsSync(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testGoogleSheetsSync(arg0);
            return result;
        }
    }
    async transformBatchUpdateResponse(arg0: TransformArgs): Promise<HttpResponsePayload> {
        if (this.processError) {
            try {
                const result = await this.actor.transformBatchUpdateResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformBatchUpdateResponse(arg0);
            return result;
        }
    }
    async transformSheetsResponse(arg0: TransformArgs): Promise<HttpResponsePayload> {
        if (this.processError) {
            try {
                const result = await this.actor.transformSheetsResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformSheetsResponse(arg0);
            return result;
        }
    }
    async transformTokenResponse(arg0: TransformArgs): Promise<HttpResponsePayload> {
        if (this.processError) {
            try {
                const result = await this.actor.transformTokenResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformTokenResponse(arg0);
            return result;
        }
    }
    async updateAttendance(arg0: string, arg1: AttendanceUpdateInput): Promise<{
        __kind__: "ok";
        ok: AttendanceRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceUpdateInput_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceUpdateInput_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePerson(arg0: string, arg1: PersonInput): Promise<{
        __kind__: "ok";
        ok: Person;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerson(arg0, to_candid_PersonInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerson(arg0, to_candid_PersonInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AttendanceRecord_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PersonType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonType): PersonType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Person_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Person): Person {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceRecord]): AttendanceRecord | null {
    return value.length === 0 ? null : from_candid_AttendanceRecord_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Person]): Person | null {
    return value.length === 0 ? null : from_candid_Person_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    afterBreak: [] | [string];
    breakTime: [] | [string];
    date: string;
    exit: [] | [string];
    entry: [] | [string];
    personId: string;
}): {
    id: string;
    afterBreak?: string;
    breakTime?: string;
    date: string;
    exit?: string;
    entry?: string;
    personId: string;
} {
    return {
        id: value.id,
        afterBreak: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.afterBreak)),
        breakTime: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.breakTime)),
        date: value.date,
        exit: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.exit)),
        entry: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.entry)),
        personId: value.personId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    semester: [] | [string];
    name: string;
    personType: _PersonType;
    nsqfLevel: [] | [string];
    faceDescriptor: Array<number>;
    rollNo: [] | [string];
    course: [] | [string];
}): {
    id: string;
    semester?: string;
    name: string;
    personType: PersonType;
    nsqfLevel?: string;
    faceDescriptor: Array<number>;
    rollNo?: string;
    course?: string;
} {
    return {
        id: value.id,
        semester: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.semester)),
        name: value.name,
        personType: from_candid_PersonType_n9(_uploadFile, _downloadFile, value.personType),
        nsqfLevel: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.nsqfLevel)),
        faceDescriptor: value.faceDescriptor,
        rollNo: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.rollNo)),
        course: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.course))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    JIG: null;
} | {
    NSQF: null;
}): PersonType {
    return "JIG" in value ? PersonType.JIG : "NSQF" in value ? PersonType.NSQF : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AttendanceRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AttendanceRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AttendanceRecord_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Person;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Person;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Person_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Person>): Array<Person> {
    return value.map((x)=>from_candid_Person_n6(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceUpdateInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceUpdateInput): _AttendanceUpdateInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PersonInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonInput): _PersonInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PersonType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonType): _PersonType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    semester?: string;
    name: string;
    personType: PersonType;
    nsqfLevel?: string;
    faceDescriptor: Array<number>;
    rollNo?: string;
    course?: string;
}): {
    semester: [] | [string];
    name: string;
    personType: _PersonType;
    nsqfLevel: [] | [string];
    faceDescriptor: Array<number>;
    rollNo: [] | [string];
    course: [] | [string];
} {
    return {
        semester: value.semester ? candid_some(value.semester) : candid_none(),
        name: value.name,
        personType: to_candid_PersonType_n3(_uploadFile, _downloadFile, value.personType),
        nsqfLevel: value.nsqfLevel ? candid_some(value.nsqfLevel) : candid_none(),
        faceDescriptor: value.faceDescriptor,
        rollNo: value.rollNo ? candid_some(value.rollNo) : candid_none(),
        course: value.course ? candid_some(value.course) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    afterBreak?: string;
    breakTime?: string;
    exit?: string;
    entry?: string;
}): {
    afterBreak: [] | [string];
    breakTime: [] | [string];
    exit: [] | [string];
    entry: [] | [string];
} {
    return {
        afterBreak: value.afterBreak ? candid_some(value.afterBreak) : candid_none(),
        breakTime: value.breakTime ? candid_some(value.breakTime) : candid_none(),
        exit: value.exit ? candid_some(value.exit) : candid_none(),
        entry: value.entry ? candid_some(value.entry) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonType): {
    JIG: null;
} | {
    NSQF: null;
} {
    return value == PersonType.JIG ? {
        JIG: null
    } : value == PersonType.NSQF ? {
        NSQF: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
